---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: "We K8s Bear"

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  labels:
    name: dov-secret
type: Opaque
data:
  INSTANCE_HASH: bXktaGFzaA==
