---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels:
    name: bggapp-cm
data:
  BGG_DB_HOST: bggdb-svc.ws3.svc.cluster.local

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bggapp-secret
  labels:
    name: bggapp-secret
data:
  BGG_DB_USER: cm9vdA==
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
