---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  labels:
    name: dov-cm
data:
  INSTANCE_NAME: "We K8s Bear"

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  labels:
    name: dov-secret
type: Opaque
data:
  INSTANCE_HASH: bXktaGFzaA==

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  labels:
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    name: dov-po
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dov-ing
  labels:
    name: dov-ing
spec:
  ingressClassName: nginx
  rules:
  - host: dov-146.190.4.201.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dov-svc
              port:
                number: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  labels:
    name: dov-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      name: dov-po
  template:
    metadata:
      name: dov-po
      labels:
        name: dov-po
    spec:
      containers:
        - name: dov-bear
          image: chukmunnlee/dov-bear:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: INSTANCE_HASH
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: dov-cm
            - secretRef:
                name: dov-secret
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
