---
apiVersion: v1
kind: Pod
metadata:
  name: dov-bear-po
  labels:
    name: dov-bear-po

spec:
  containers:
    - name: dov-bear
      # image: suwarno/dov-bear:1.0.0
      image: chukmunnlee/dov-bear:v1golang
      imagePullPolicy: IfNotPresent
      env:
        - name: INSTANCE_NAME
          value: "We K8s Bear"
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
