---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: ClusterIP
  selector:
    name: bggapp-po
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy

spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-po

  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
    spec:
      containers:
        - name: bggapp
          image: stackupiss/bgg-backend:v1
          envFrom:
            - configMapRef:
                name: bggapp-cm
            - secretRef:
                name: bggapp-secret
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
